version: '3.8'
services:
  product:
    build: ./product
    ports:
      - "5001:5001"
    networks:
      - ecommerce-network
  
  order:
    build: ./order
    ports:
      - "5002:5002"
    networks:
      - ecommerce-network

  user:
    build: ./user
    ports:
      - "5003:5003"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
